# k8s/deployment.yaml
apiVersion: apps/v1
kind: Deployment
metadata:
  name: nginx-deployment
  labels:
    app: nginx
spec:
  replicas: 1
  selector:
    matchLabels:
      app: nginx
  template:
    metadata:
      labels:
        app: nginx
    spec:
      # This is the intentional error for our first run
      serviceAccountName: non-existent-sa
      containers:
      - name: nginx
        image: nginx:1.25.2
        ports:
        - containerPort: 80
