name: ARC Node Autoscaling Test

on:
  workflow_dispatch:

jobs:
  stress-test:
    # IMPORTANT: Ensure 'arc-runner-set' matches the label used by your
    # HorizontalRunnerAutoscaler or RunnerDeployment.
    runs-on: aks-3-arc-runner-set
    timeout-minutes: 20
    

    strategy:
      matrix:
        job_id: [1, 2, 3, 4]
      fail-fast: false

    # The 'container:' block has been removed.
    # The steps below will now run directly on the runner pod's OS.

    steps:
      - name: Install stress-ng tool
        run: |
          echo "Installing dependencies for Job ID: ${{ matrix.job_id }}"
          sudo apt-get update -y
          sudo apt-get install -y stress-ng

      - name: Consume CPU and Memory for 5 minutes
        run: |
          echo "Starting resource consumption for Job ID: ${{ matrix.job_id }}"
          stress-ng --cpu 1 --vm 1 --vm-bytes 1G --timeout 300s
          echo "Job ID: ${{ matrix.job_id }} has finished."
