name: Lock or Unlock Branch - 2

on:
  workflow_dispatch:
    inputs:
      action:
        description: "Action to perform: lock or unlock"
        required: true
        type: choice
        options:
        - lock
        - unlock
      user:
        description: "Username to be the ONLY one allowed to push (for lock action)"
        required: false # Only required for lock
      branch:
        description: "Branch to protect"
        required: true
        default: "main"

jobs:
  manage-branch-protection:
    runs-on: ubuntu-latest
    
    # Grant permissions to modify administration settings like branch protection
    steps:
      - name: Set up GitHub CLI
        run: echo "${{ secrets.ADMIN_PAT }}" | gh auth login --with-token

      - name: Lock Branch
        if: github.event.inputs.action == 'lock'
        run: |
          if [ -z "${{ github.event.inputs.user }}" ]; then
            echo "Error: Username is required for the 'lock' action."
            exit 1
          fi
          response=$(curl -L \
            -X PUT \
            -H "Accept: application/vnd.github+json" \
            -H "Authorization: Bearer ${{ secrets.ADMIN_PAT }}" \
            -H "X-GitHub-Api-Version: 2022-11-28" \
            -d '{
              "required_status_checks": null,
              "enforce_admins": true,
              "required_pull_request_reviews": {
                "dismissal_restrictions": {
                  "users": ["${{ github.event.inputs.user }}"],
                  "teams": [],
                  "apps": []
                },
                "dismiss_stale_reviews": true,
                "require_code_owner_reviews": false,
                "required_approving_review_count": 1,
                "require_last_push_approval": false,
                "bypass_pull_request_allowances": {
                  "users": ["${{ github.event.inputs.user }}"],
                  "teams": [],
                  "apps": []
                }
              },
              "restrictions": {
                "users": ["${{ github.event.inputs.user }}"],
                "teams": [],
                "apps": []
              },
              "required_linear_history": false,
              "allow_force_pushes": false,
              "allow_deletions": false,
              "block_creations": false,
              "required_conversation_resolution": false,
              "lock_branch": false,
              "allow_fork_syncing": false
            }' \
            https://api.github.com/repos/${{ github.repository }}/branches/${{ github.event.inputs.branch }}/protection \
            -o response.json \
            -w "%{http_code}")
            
          if [ "$response" -ne 200 ]; then
            cat response.json
            echo "Failed to lock branch ${{ github.event.inputs.branch }}. HTTP status: $response"
            exit 1
          fi
          echo "Branch ${{ github.event.inputs.branch }} is now locked."
      
      - name: Unlock Branch
        if: github.event.inputs.action == 'unlock'
        run: |
          # The 'unlock' action is simply deleting the branch protection rules
          gh api \
            --method DELETE \
            -H "Accept: application/vnd.github+json" \
            "/repos/${{ github.repository }}/branches/${{ github.event.inputs.branch }}/protection"
          echo " Branch ${{ github.event.inputs.branch }} is now unlocked."
